name: Build and package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/Hydrogen"

      - name: Install dependencies
        run: npm install

      - name: Copyright check
        run: npm run copyright-check

      - name: Typecheck
        run: npm run typecheck

      - name: Build Package
        run: npm run build

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: extension-package
          path: dist
